version: '3.3'

services:
    pgdb:
        container_name: pgdb
        image: postgres:latest
        env_file: 
            - database.env
        ports:
            - 5432:5432
        volumes:
            - database-data:/var/lib/postgresql/data/
        networks: 
            - app_net

    rk:
        container_name: rk
        build:
            context: ../
            dockerfile: docker/Dockerfile
        ports:
            - 8002:8002
        environment: 
            - BASE_DIR=/opt/data
        volumes:
            - ../repos:/opt/data
        networks: 
            - app_net

volumes: 
    database-data:

networks:
    app_net:
        driver: bridge